version: "3.9"
services:
  chat_db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: chat_db

  redis-db:
    image: redis:7.0.5-alpine
    ports:
      - "16379:6379"

  consul:
    image: consul:1.15
    ports:
      - 8500:8500

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  channel_service:
    build:
      dockerfile: ./services/channel_service/Dockerfile.dev
    environment:
      APP_ENV: dev
      DB_DRIVER: postgres
      DB_DSN: ${DB_DSN}
      CONSUL_HOST: consul:8500
      JAEGER_HOST: http://jaeger:14268/api/traces
      REDIS_URI: redis://redis-db:6379

  chat_scheduler:
    build:
      dockerfile: services/chat_service/cmd/chat_scheduler/Dockerfile.dev
    environment:
      APP_ENV: dev
      DB_DRIVER: postgres
      DB_DSN: postgresql://postgres:123123123@chat_db/chat_db?sslmode=disable
      CONSUL_HOST: consul:8500
      JAEGER_HOST: http://jaeger:14268/api/traces
      REDIS_URI: redis://redis-db:6379

