version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  channel_service:
    cmds:
      - cd services/channel_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop main.go
      - defer: cd services/channel_service && rm jetshop
      - docker-compose build channel_service
      - docker-compose up channel_service

  chat_scheduler:
    cmds:
      - cd services/chat_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop cmd/chat_scheduler/main.go
      - defer: cd services/chat_service && rm jetshop
      - docker-compose build chat_scheduler
      - docker-compose up chat_scheduler

  chat_sync_thread_consumer:
    cmds:
      - cd services/chat_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop cmd/chat_sync_thread_consumer/main.go
      - defer: cd services/chat_service && rm jetshop
      - docker-compose build chat_sync_thread_consumer
      - docker-compose up chat_sync_thread_consumer

  chat_detail_thread_consumer:
    cmds:
      - cd services/chat_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop cmd/chat_detail_thread_consumer/main.go
      - defer: cd services/chat_service && rm jetshop
      - docker-compose build chat_detail_thread_consumer
      - docker-compose up chat_detail_thread_consumer

  chat_update_thread_consumer:
    cmds:
      - cd services/chat_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop cmd/chat_update_thread_consumer/main.go
      - defer: cd services/chat_service && rm jetshop
      - docker-compose build chat_update_thread_consumer
      - docker-compose up chat_update_thread_consumer

  chat_migrate:
    cmds:
      - cd services/chat_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop cmd/chat_migrate/main.go
      - defer: cd services/chat_service && rm jetshop
      - docker-compose build chat_migrate
      - docker-compose up chat_migrate
