version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  channel_service:
    cmds:
      - cd services/channel_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop main.go
      - defer: cd services/channel_service && rm jetshop
      - docker-compose build channel_service
      - docker-compose up channel_service

  chat_service:
    cmds:
      - cd services/chat_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o jetshop main.go
      - defer: cd services/chat_service && rm jetshop
      - docker-compose build chat_service
      - docker-compose up chat_service
